version: '2'
services:
 lb1:
    image: rancher/load-balancer-service
    ports:
    - 8081:80

 reactive-app01:
    image: an3ll/kotlin-reactive-app
    ports:
      - 8081:8080

 reactive-app02:
    image: an3ll/kotlin-reactive-app
    ports:
      - 8082:8080